### ISSUE TITLE
Docs plugin is broken with boot 2.0 apps upgrade

### ISSUE THREAD

**Issue by sobychacko** [spring-cloud/spring-cloud-app-starters-maven-plugins#20]

**Comment by sobychacko** [comment]
Seeing this exception when generating the docs: 
```
Caused by: org.apache.maven.plugin.MojoExecutionException: Error generating documentation
	at org.springframework.cloud.stream.app.documentation.plugin.ConfigurationMetadataDocumentationMojo.execute(ConfigurationMetadataDocumentationMojo.java:138)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 27 more
Caused by: java.lang.NullPointerException
```

**Comment by artembilan** [comment]
The closer stack trace is like this:
```
Caused by: org.apache.maven.plugin.MojoExecutionException: Error generating documentation
        at org.springframework.cloud.stream.app.documentation.plugin.ConfigurationMetadataDocumentationMojo.execute(ConfigurationMetadataDocumentationMojo.java:138)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 27 more
Caused by: java.lang.NullPointerException
        at org.springframework.cloud.stream.app.documentation.plugin.ConfigurationMetadataDocumentationMojo.maybeHints(ConfigurationMetadataDocumentationMojo.java:175)
        at org.springframework.cloud.stream.app.documentation.plugin.ConfigurationMetadataDocumentationMojo.asciidocFor(ConfigurationMetadataDocumentationMojo.java:159)
        at org.springframework.cloud.stream.app.documentation.plugin.ConfigurationMetadataDocumentationMojo.execute(ConfigurationMetadataDocumentationMojo.java:119)
        ... 29 more
```
